export const PHI_FIELD_BANLIST = [
  "patientName",
  "patient_name",
  "firstName",
  "first_name",
  "lastName",
  "last_name",
  "phone",
  "phoneNumber",
  "mobile",
  "email",
  "mrn",
  "medicalRecordNumber",
  "medical_record_number",
  "ssn",
  "insurance",
  "insuranceNumber",
  "insurance_number",
  "policyNumber",
  "policy_number",
  "dob",
  "dateOfBirth",
  "date_of_birth",
  "address",
  "diagnosis",
  "complaint",
  "chiefComplaint",
  "allergy",
  "allergies",
  "clinicalNote",
  "clinicalText",
  "prescription",
  "complaints",
  "findings",
  "diagnosisText",
  "diagnosis_text",
  "advice",
  "followUp",
  "follow_up",
  "medicationText",
  "medication_text",
  "medicationName",
  "medication_name",
  "labResult",
  "paymentDetails"
] as const;

export type PhiFieldName = (typeof PHI_FIELD_BANLIST)[number];
