export const CLINICAL_ARTIFACT_STATUS = {
  PRELIMINARY: "preliminary",
  SIGNED: "signed",
  SUPERSEDED: "superseded"
} as const;

export const CLINICAL_ARTIFACT_STATUSES = [
  CLINICAL_ARTIFACT_STATUS.PRELIMINARY,
  CLINICAL_ARTIFACT_STATUS.SIGNED,
  CLINICAL_ARTIFACT_STATUS.SUPERSEDED
] as const;

export const NOTE_TEXT_LIMIT = 10_000;

export const PRESCRIPTION_TEXT_LIMIT = 500;
