import { sql } from "drizzle-orm";
import {
  boolean,
  date,
  inet,
  integer,
  jsonb,
  numeric,
  pgEnum,
  text,
  timestamp,
  uuid,
  varchar,
} from "drizzle-orm/pg-core";

/**
 * Shared schema primitives for Arogya OS.
 *
 * Conventions:
 * - All PHI-bearing domain tables carry tenantId/facilityId where applicable.
 * - Domain primary keys are UUIDs generated by Postgres.
 * - Better Auth tables retain string IDs because Better Auth owns those models.
 * - Canonical clinical data lives in fhirResourceVersions; projections are derived/hot-path read models.
 * - Money is numeric(14,2) as string in Drizzle to avoid JS float drift.
 * - Timestamps are timestamptz.
 */

export const lifecycleStatus = pgEnum("lifecycle_status", [
  "draft",
  "active",
  "inactive",
  "archived",
  "deleted",
]);

export const dataClassification = pgEnum("data_classification", [
  "public",
  "internal",
  "pii",
  "phi",
  "financial",
  "security",
]);

export const tenantDeploymentModel = pgEnum("tenant_deployment_model", [
  "shared_saas",
  "dedicated_tenant",
  "dedicated_cluster",
  "customer_managed",
]);

export const tenantLifecycleStatus = pgEnum("tenant_lifecycle_status", [
  "prospect",
  "design_partner",
  "sandbox",
  "onboarding",
  "live",
  "suspended",
  "offboarding",
  "terminated",
]);

export const actorType = pgEnum("actor_type", [
  "user",
  "patient",
  "service",
  "api_key",
  "edge_device",
  "external_system",
  "ai_model",
]);

export const policyDecision = pgEnum("policy_decision", ["allow", "deny", "break_glass_allow"]);

export const purposeOfUse = pgEnum("purpose_of_use", [
  "treatment",
  "payment",
  "healthcare_operations",
  "patient_request",
  "audit",
  "support",
  "emergency",
  "research_deidentified",
  "integration",
]);

export const fhirResourceStatus = pgEnum("fhir_resource_status", [
  "preliminary",
  "final",
  "amended",
  "entered_in_error",
  "superseded",
]);

export const syncStatus = pgEnum("sync_status", [
  "pending",
  "in_progress",
  "succeeded",
  "failed",
  "dead_lettered",
  "cancelled",
]);

export const eventPublishStatus = pgEnum("event_publish_status", [
  "pending",
  "published",
  "failed",
  "dead_lettered",
  "replayed",
]);

export const consentStatus = pgEnum("consent_status", [
  "draft",
  "requested",
  "granted",
  "denied",
  "active",
  "revoked",
  "expired",
  "superseded",
]);

export const encounterClass = pgEnum("encounter_class", ["opd", "ipd", "er", "telehealth", "home_visit"]);

export const encounterStatus = pgEnum("encounter_status", [
  "planned",
  "arrived",
  "triaged",
  "in_progress",
  "on_hold",
  "finished",
  "cancelled",
  "entered_in_error",
]);

export const appointmentStatus = pgEnum("appointment_status", [
  "proposed",
  "pending",
  "booked",
  "arrived",
  "fulfilled",
  "cancelled",
  "noshow",
  "waitlist",
]);

export const queueTokenStatus = pgEnum("queue_token_status", [
  "issued",
  "checked_in",
  "called",
  "in_consult",
  "skipped",
  "completed",
  "cancelled",
]);

export const paymentStatus = pgEnum("payment_status", [
  "pending",
  "authorized",
  "captured",
  "failed",
  "refunded",
  "partially_refunded",
  "voided",
  "reconciled",
]);

export const invoiceStatus = pgEnum("invoice_status", [
  "draft",
  "finalized",
  "partially_paid",
  "paid",
  "voided",
  "refunded",
  "written_off",
]);

export const claimStatus = pgEnum("claim_status", [
  "draft",
  "preauth_requested",
  "preauth_approved",
  "preauth_rejected",
  "assembled",
  "submitted",
  "queried",
  "approved",
  "partially_approved",
  "rejected",
  "settled",
  "cancelled",
]);

export const aiArtifactStatus = pgEnum("ai_artifact_status", [
  "captured",
  "processing",
  "draft",
  "needs_review",
  "accepted",
  "rejected",
  "deleted",
  "failed",
]);

export const aiReviewOutcome = pgEnum("ai_review_outcome", [
  "accepted_no_edits",
  "accepted_minor_edits",
  "accepted_major_edits",
  "rejected",
  "not_reviewed",
]);

export const safetySeverity = pgEnum("safety_severity", [
  "info",
  "low",
  "moderate",
  "high",
  "severe_blocking",
]);

export const objectStorageProvider = pgEnum("object_storage_provider", [
  "s3",
  "gcs",
  "azure_blob",
  "local_minio",
]);

export const integrationKind = pgEnum("integration_kind", [
  "abdm",
  "nhcx",
  "whatsapp_bsp",
  "sms",
  "payment_gateway",
  "stt_vendor",
  "llm_vendor",
  "lis_hl7v2",
  "pharmacy_hl7v2",
  "pacs_dicom",
  "email",
]);

export const integrationEnvironment = pgEnum("integration_environment", [
  "mock",
  "sandbox",
  "staging",
  "production",
]);

export const integrationMessageDirection = pgEnum("integration_message_direction", [
  "inbound",
  "outbound",
]);

export const migrationRunStatus = pgEnum("migration_run_status", [
  "draft",
  "validating",
  "validated",
  "importing",
  "succeeded",
  "succeeded_with_warnings",
  "failed",
  "rolled_back",
]);

export const supportAccessStatus = pgEnum("support_access_status", [
  "requested",
  "approved",
  "active",
  "expired",
  "revoked",
  "denied",
]);

export const edgeDeviceStatus = pgEnum("edge_device_status", [
  "provisioned",
  "active",
  "degraded",
  "offline",
  "quarantined",
  "revoked",
]);

export const jobPriority = pgEnum("job_priority", ["low", "normal", "high", "critical"]);

export const exportStatus = pgEnum("export_status", [
  "requested",
  "approved",
  "running",
  "succeeded",
  "failed",
  "expired",
  "cancelled",
]);

export const timestampColumns = {
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
};

export const softDeleteColumns = {
  deletedAt: timestamp("deleted_at", { withTimezone: true }),
  deletedByUserId: text("deleted_by_user_id"),
  deletionReason: text("deletion_reason"),
};

export const auditActorColumns = {
  createdByUserId: text("created_by_user_id"),
  updatedByUserId: text("updated_by_user_id"),
};

export const tenantScopeColumns = {
  tenantId: uuid("tenant_id").notNull(),
};

export const facilityScopeColumns = {
  facilityId: uuid("facility_id"),
};

export const encryptionColumns = {
  encryptionKeyId: text("encryption_key_id"),
  encryptionKeyVersion: integer("encryption_key_version"),
  encryptedDek: text("encrypted_dek"),
};

export const requestTraceColumns = {
  requestId: text("request_id"),
  traceId: text("trace_id"),
  spanId: text("span_id"),
};

export const networkColumns = {
  ipAddress: inet("ip_address"),
  userAgent: text("user_agent"),
  deviceId: text("device_id"),
};

export const money = (name: string) => numeric(name, { precision: 14, scale: 2 });
export const quantity = (name: string) => numeric(name, { precision: 14, scale: 4 });
export const percent = (name: string) => numeric(name, { precision: 7, scale: 4 });

export const jsonbObj = <T extends Record<string, unknown> = Record<string, unknown>>(name: string) =>
  jsonb(name).$type<T>();

export const jsonbArray = <T = unknown>(name: string) => jsonb(name).$type<T[]>();

export const dateOnly = (name: string) => date(name, { mode: "string" });

export const activeCheck = (column: { deletedAt?: unknown }) => sql`deleted_at is null`;

export type JsonRecord = Record<string, unknown>;
